/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author saulr
 */
public class FrmPanelCentral extends javax.swing.JFrame {

    /**
     * Creates new form FrmPanelCentral
     */
    FrmFacultad admFacultad;
    FrmCarrera admCarrera;
    FrmEstudiante admEstudiante;
    
    public FrmPanelCentral() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenuFacultades = new javax.swing.JMenu();
        jMenuGF = new javax.swing.JMenuItem();
        jMenuCarreras = new javax.swing.JMenu();
        jMenuGC = new javax.swing.JMenuItem();
        jMenuEstudiantes = new javax.swing.JMenu();
        jMenuGE = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuFacultades.setText("Facultades");
        jMenuFacultades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuFacultadesMouseClicked(evt);
            }
        });

        jMenuGF.setText("Gestionar Facultades");
        jMenuGF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuGFActionPerformed(evt);
            }
        });
        jMenuFacultades.add(jMenuGF);

        jMenuBar2.add(jMenuFacultades);

        jMenuCarreras.setText("Carreras");
        jMenuCarreras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCarrerasActionPerformed(evt);
            }
        });

        jMenuGC.setText("Gestionar Carreras");
        jMenuGC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuGCActionPerformed(evt);
            }
        });
        jMenuCarreras.add(jMenuGC);

        jMenuBar2.add(jMenuCarreras);

        jMenuEstudiantes.setText("Estudiantes");

        jMenuGE.setText("Gestionar Estudiantes");
        jMenuGE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuGEActionPerformed(evt);
            }
        });
        jMenuEstudiantes.add(jMenuGE);

        jMenuBar2.add(jMenuEstudiantes);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuFacultadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuFacultadesMouseClicked
        
    }//GEN-LAST:event_jMenuFacultadesMouseClicked

    private void jMenuGEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuGEActionPerformed
        if(this.admEstudiante == null || this.admEstudiante.isClosed())
        {
            try {
                this.admEstudiante = new FrmEstudiante();
            } catch (Exception e) 
            {
                
            }
            this.admEstudiante.setVisible(true);
            this.jDesktopPane.add(admEstudiante);
        }
    }//GEN-LAST:event_jMenuGEActionPerformed

    private void jMenuGFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuGFActionPerformed
        if(this.admFacultad == null || this.admFacultad.isClosed())
        {
            try {
                this.admFacultad = new FrmFacultad();
            } catch (Exception e) 
            {
                
            }
            this.admFacultad.setVisible(true);
            this.jDesktopPane.add(admFacultad);
        }
    }//GEN-LAST:event_jMenuGFActionPerformed

    private void jMenuCarrerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCarrerasActionPerformed
        if(this.admCarrera == null || this.admCarrera.isClosed())
        {
            try {
                this.admCarrera = new FrmCarrera();
            } catch (Exception e) 
            {
                
            }
            this.admCarrera.setVisible(true);
            this.jDesktopPane.add(admCarrera);
        }
    }//GEN-LAST:event_jMenuCarrerasActionPerformed

    private void jMenuGCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuGCActionPerformed
         if(this.admCarrera == null || this.admCarrera.isClosed())
        {
            try {
                this.admCarrera = new FrmCarrera();
            } catch (Exception e) 
            {
                
            }
            this.admCarrera.setVisible(true);
            this.jDesktopPane.add(admCarrera);
        }
    }//GEN-LAST:event_jMenuGCActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu jMenuCarreras;
    private javax.swing.JMenu jMenuEstudiantes;
    private javax.swing.JMenu jMenuFacultades;
    private javax.swing.JMenuItem jMenuGC;
    private javax.swing.JMenuItem jMenuGE;
    private javax.swing.JMenuItem jMenuGF;
    // End of variables declaration//GEN-END:variables

}
